Other refinements
entando/entando-test-automation pull request #104
Opened 2022-03-30 13:06 UTC by riccardo-fadda

2022-03-30 14:10 UTC, g-di-martino requested changes

2022-03-30 14:10 UTC, g-di-martino commented on ui-tests/cypress/integration/pages/management.spec.js
> +    cy.get('@subPageToBeDeleted').then(subPageToBeDeleted => {
Wrap the actual subPage to be deleted instead of relying on the _let_ variable

2022-03-30 14:10 UTC, g-di-martino commented on ui-tests/cypress/integration/pages/widgets-ootb.spec.js
>      // TODO: solve on how to make cypress access sites using `cy.visit` with different ports
Have you tried to investigate this?

2022-03-30 14:10 UTC, g-di-martino commented on ui-tests/cypress/integration/pages/widgets-ootb.spec.js
> +    /*const WIDGET_FRAME_2 = {
Why is this commented?

2022-03-30 14:10 UTC, g-di-martino commented on ui-tests/cypress/integration/pages/widgets-ootb.spec.js
> +    // TODO: not working until the cms structure is updated
👆🏼

2022-04-04 07:34 UTC, riccardo-fadda commented on ui-tests/cypress/integration/myProfile/my-profile.spec.js
> +    xit('Preferences - set preferences', () => {
Fixed

2022-04-04 07:34 UTC, riccardo-fadda commented on ui-tests/cypress/integration/pages/management.spec.js
> +          cy.wrap(true).as('subPageToBeDeleted');
Fixed to store the subPage code

2022-04-04 07:34 UTC, riccardo-fadda commented on ui-tests/cypress/integration/pages/management.spec.js
> +            .then(() => cy.wrap(true).as('pageToBeDeleted'));
Fixed to store the page code

2022-04-04 07:35 UTC, riccardo-fadda commented on ui-tests/cypress/integration/pages/widgets-ootb.spec.js
>      // TODO: solve on how to make cypress access sites using `cy.visit` with different ports
Edited the cy visit command

2022-04-04 07:36 UTC, riccardo-fadda commented on ui-tests/cypress/integration/pages/widgets-ootb.spec.js
> +    // FIXME/TODO: the PUT request for the "entando_apis" widget to revert the widget
Fixed, a parameter was missing

2022-04-04 08:43 UTC, g-di-martino approved these changes

2022-04-04 08:43 UTC, merged